### ISSUE TITLE
Add support for controlling the camera torch

### ISSUE THREAD

**Issue by erlingfjelstad** [pexip/pexip-android-sdk#206]
### Is your feature request related to a problem? Please describe.

We want to use this SDK for a medical use-case where we do video calls outdoors in when it's dark. Therefore we would like to utilize the torch to get some more light. 

### Describe the solution you would like

Extend CameraVideoTrack as such:

`
public interface CameraVideoTrack : LocalVideoTrack {
...
public fun toggleTorch(callback: TorchCallback)

public interface TorchCallback {
   public fun onSuccess(enabled: Boolean)
   public fun onFailure(error: String)
}
}
`

### Describe alternatives you have considered

Using another SDK :/

**Comment by drymarau** [comment]
Hi @erlingfjelstad and thank you for your suggestion. It's definitely something we'd like to do, but still undecided on both API shape and implementation. As will all things camera, it might be some time before we can offer anything in the SDK.

In the meantime, we've been using [`WebRtcMediaConnectionFactory.createLocalVideoTrack`](https://github.com/pexip/pexip-android-sdk/blob/7201f52ec01861266b560f21fa5702cca0312b79/sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt#L205) in one of our apps to get access to torch by providing a custom implementation of `VideoCapturer` based on WebRTC's [`Camera2Capturer`](https://webrtc.googlesource.com/src/+/refs/heads/main/sdk/android/api/org/webrtc/Camera2Capturer.java) that exposes torch and zoom controls.
