### ISSUE TITLE
Need for participant events

### ISSUE THREAD

**Issue by ajf101** [pexip/pexip-android-sdk#209]
### Is your feature request related to a problem? Please describe.

We need to develop an application that acts upon changes in the participant list, and thus need to be fed events as participants join and leave.

### Describe the solution you would like

For there to be a callback available in the SDK for participant join/leave/change.

**Comment by drymarau** [comment]
This has been implemented as part of [0.15.0](https://github.com/pexip/pexip-android-sdk/releases/tag/0.15.0) via [`Roster`](https://pexip.github.io/pexip-android-sdk/sdk-conference/com.pexip.sdk.conference/-roster/index.html).

Note that underlying events are not exposed. An observable participant list is available is though and it's possible to infer added and removed participants via various collections functions available in standard library.
